package com.softeng.ooyoo.helpers

val INTERESTS_ARRAY_LIST = arrayListOf(
    "Chess",
    "Hiking",
    "Meditation",
    "Anime",
    "Tuvan throat singing",
    "Books",
    "Science fiction",
    "Gaming",
    "Sports",
    "Music",
    "Conspiracy theories",
    "Yoga",
    "Board games",
    "Movies",
    "Museum",
    "Laser tag",
    "Internet",
    "Photography",
    "Painting",
    "Writing",
    "Walking in nature",
    "Cooking",
    "Cocooning",
    "Calligraphy",
    "Coin collection",
    "Shopping",
    "Making sock-bunnies"
)